coupled/atmos_model.F90
Fixes missing quote in coupled/atmos_model.F90
Compile tests on gaea
**Checklist:**
=> added missing quotes in coupled/atmos_model.F90

SHiELD/atmos_model.F90, solo/atmos_model.F90
Fixes a bug in SHiELD/atmos_model for variable initialization.
In solo/atmos_model:
- updates module use handling 
- removes outdated logic for data_override_init handling
- gives calendar an initial value
DEPENDENCY ON [FMS PR #933](https://github.com/NOAA-GFDL/FMS/pull/933)
This has been tested in FV3 solo tests to ensure proper handling of data_override_init with no grid_spec and an empty data_table.  The variable initialization bug in SHiELD has been tested in a SHiELD run.
**Checklist:**
=> Bug fixes and data_override logic updates

SHiELD/atmos_model.F90
Add in logic to allow for better IO read performance when io_layout=(1,1).   The fix is to create an mpp_domain for reading that sets io_layout=layout.  There is also a change to allow data integrity restart checksums to be overridden.
If at all possible, I'd like to see this implemented with the 2022.02 tag.
This has been tested in a prototype test to understand the valid use cases for this capability.  The prototype logic was implemented within SHiELD and tests run to validate.  The data integrity checks had previously been tested from within an FMS CI unit test.
**Checklist:**
=> updates to SHiELD atmosphere driver

SHiELD/atmos_model.F90
Jan-Huey discovered a nasty bug in the SHiELD driver: if first_time_step is true, then physics diagnostics are written on EVERY timestep. Also, since first_time_step defaults to true, if it is not explicitly set to false, then the problem occurs too, without any indication what is happening.
Jan-Huey discovered a nasty bug in the SHiELD Model driver in atmos_model.F90 . If first_time_step is true, then physics diagnostics are written on EVERY timestep. This creates far more history file output than we want.
But also, since first_time_step defaults to true, if it is not explicitly set to false, then the problem occurs too, without any indication what is happening. This creates a very obscure issue that is hard to debug.
Ran a test without …
=> Fix for invisible first_time_step bug in SHiELD

solo/atmos_model.F90
There was one final fmsio call remaining in solo/atmos_model.F90.  This PR removes it.
Fixes #20 
Tested with the SHiELD solo idealized tests with intel on gaea c4.
**Checklist:**
=> Deprecated fmsio

SHiELD/atmos_model.F90
The dynamical core and physics package share some namelist variables. In the current model codebase, these namelist variables are either passed from the dynamical core to the physics package after the initialization or duplicated in the physics package. This produces a potential issue that the physics initialization does not see the dynamical core namelist and leads to errors.
No issue with this atmos_drivers. We need some code changes in atmos_drivers so that our update of the dynamical core and physics package will work.
It was tested and the results are expected. The issue has been resolved.
**Checklist:**
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- My changes …
=> Pass the namelist variables from the dycore to the physics during the initialization

SHiELD/atmos_model.F90
This PR and PR https://github.com/NOAA-GFDL/SHiELD_physics/pull/26 address the following comment from the review of PR https://github.com/NOAA-GFDL/SHiELD_physics/pull/22:
"The designed way to get this information to the physics from outside is to use the GFS_init_type. This type is populated with dycore and other external to the physics information within the atmos_model.F90::atmos_model_init function and it is passed to GFS_Initialize, where it is passed to the Model%init procedure."
**Checklist:**
=> Revised type of a few variables

solo/atmos_model.F90
solo/atmos_model.F90 uses the FMS module.  In FMS 2023.02-beta1 this module has aliased all functions to contain a prefix before the function name.  This PR changes to the new naming convention so that the code can compile with FMS 2023.02-beta2.
Tested with SHiELD solo tests on Gaea with intel
**Checklist:**
=> Update solo/atmos_model.F90 for FMS module new aliasing

SHiELD/atmos_model.F90
This PR makes the `Atm_block`, `IPD_control`, and `IPD_data` structures public in `SHiELD/atmos_model.F90`.  This is needed for interaction within the Python-wrapped version of SHiELD under development starting with ai2cm/SHiELD-wrapper#1.
These changes have been tested in https://github.com/ai2cm/SHiELD-wrapper/pull/1. The continuous integration setup there builds the fortran model and its dependencies using the SHiELD_build `COMPILE` script, builds the Python wrapper, and runs several tests, including some that leverage interaction with these structures.
**Checklist:**
=> Make `Atm_block`, `IPD_control`, and `IPD_Data` public in `SHiELD/atmos_model.F90`

SHiELD/atmos_model.F90
Per our discussion today, this surfaces what is discussed in #27 as a PR for greater visibility (marking as a draft for now pending possible overlapping work by @JosephMouallem).  It splits the `update_atmos_radiation_physics` subroutine into three parts:
- `update_atmos_pre_radiation`
- `update_atmos_radiation`
- `update_atmos_physics`
The `update_atmos_radiation_physics` subroutine is retained and does exactly what it did before (so this does not change answers and requires no downstream code changes), but is written in a more modular fashion, exposing its steps as additional public subroutines in `atmos_model_mod`.
Fixes #27
xref: https://github.com/ai2cm/fv3gfs-fortran/pull/317 for how we proceeded with this in FV3GFS.
On top of the …
=> Split `update_atmos_radiation_physics` in `SHiELD/atmos_model.F90`

SHiELD/atmos_model.F90
See NOAA-GFDL/SHiELD_physics#31 for more details regarding context and testing.
cc: @lharris4
**Checklist:**
=> Pass `override_surface_radiative_fluxes` flag to `gfdl_diag_register`

coupled/atmos_model.F90
This PR is linked to issue #28 and it depends on issue #92 (#93) of the FMScoupler repository.
A new boundary layer scheme (NCEP TKE-based eddy-diffusivity mass-flux scheme) is being implemented in the prototype-AM5 model, and it requires five additional surface variables (shflx, lhflx, wind, thv_atm, and thv_surf) as inputs. Thus, I would like to add a few lines in the atmos_driver (coupled/atmos_model.F90) to pass these variables into the physics driver. (A "ifdef" statement is added to maintain backward compatibility with AM4's physics driver).
The AM4 8-day 'basic' run with my **updated FMScoupler and atmos_drivers** can bitwise reproduce the results with those run with the default code. This test is done with the AM4-2023.02 xml obtained …
=> Passing additional surface variables into the atmospheric model #28

SHiELD/atmos_model.F90
This small PR is required for compatibility with NOAA-GFDL/SHiELD_physics#36.  See the PR description there for more details regarding what this is for and how it was tested.
**Checklist:**
=> Enable outputting surface type fraction diagnostics from SHiELD

SHiELD/atmos_model.F90
This PR accompanies https://github.com/NOAA-GFDL/SHiELD_physics/pull/39.  It is required to be able to access the `ldiag3d` attribute from within `register_diag_manager_controlled_diagnostics`.
See https://github.com/NOAA-GFDL/SHiELD_physics/pull/39.
**Checklist:**
=> Pipe `IPD_Control` into `register_diag_manager_controlled_diagnostics`

solo/atmos_model.F90
Adds a call to `diag_send_complete` to the solo driver so that it can work with the new diag manager
SHiELD tests were ran by @abrooks1085 
**Checklist:**
=> Add diag_send_complete to the solo driver

SHiELD/atmos_model.F90
This PR implements the solution proposed in #35 to allow running SHiELD simulations for substantially longer than 68 years.  It is difficult to estimate a firm upper bound on what the simulation length can be now; if this were the only limitation then runs up to 5.8 million years could be completed, but there are likely other places where the model would fail first.  There is [another place](https://github.com/NOAA-GFDL/SHiELD_physics/blob/5e5e100c068d55b8247dcb428f9df36fb31bdf35/GFS_layer/GFS_driver.F90#L316) where seconds are used as a time unit to record the total length of the simulation, but there the time is recorded using a 64-bit floating point value, so we do risk overflow.
Fixes #35 
cc: @lharris4 
I have tested this and confirmed …
=> Enable SHiELD simulations longer than ~68 years

SHiELDFULL/atmos_model.F90, coupled/atmos_model.F90
Add `t_ocean` and `rough_heat` to the data structure `land_ice_atmos_boundary_type` to accommodate https://github.com/NOAA-GFDL/FMScoupler/pull/143 for shield/mom6 coupling
=> add t_ocean and rough_heat

SHiELDFULL/atmos_model.F90
There are a few updates in the PR.
1.  A new procedure has been introduced to pass surface shortwave, longwave and precip fluxes from SHiELD physics to the coupler is introduced. Physical field exchange between atmosphere and ocean is now complete.
2. The procedure for passing surface air-sea fluxes to SHiELD physics has been moved within the "if dycore_only" switch.
3. Ensure that the "sfc_coupled" option in SHiELD physics is set correctly based on whether ocean coupling is used.
=> Surface radiation and precip fluxes exchange

SHiELD/atmos_model.F90
Fixes two bugs:
- The `do_diss_est` flag would be hard-coded to equal `do_skeb`, meaning that this would never be enabled if stochastic physics were not turned on.
- SHiELD running with the option `dycore_only=.T.` would call `mpp_clock_begin(shieldClock)` but not `mpp_clock_end(shieldClock)` in each call to `update_atmos_pre_radiation()`, causing a FATAL error.
Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.
**Checklist:**
=> do_diss_est and dycore_only bugfixes

SHiELDFULL/atmos_model.F90
In the `SHiELDFULL/atmos_model.F90` `atmos_model_restart` subroutine, I have added calls to `set_atmosphere_pelist` before writing restarts, and `mpp_set_current_pelist` after.  This gets us past a model hang when using a global nest configuration with SHiELDFULL.
Tested on Gaea with a global nest SHiELD experiment provided to me by @kaiyuan-cheng 
**Checklist:**
=> Fix model hang when writing intermediate restarts in SHiELDFULL nest experiment

SHiELDFULL/atmos_model.F90
For certain PE layouts, incorrect data was written to some fields on the exchange grid. Investigation revealed that the issue is caused by the `gust` variable not being initialized in the coupled SHiELD driver, even though it is used in `surface_flux.F90`.
In the coupled driver, `gust` is populated at a different stage in`atmos_model_init`, so that driver probably doesnt have this issue.
=> Initialize gust for coupled shield

SHiELDFULL/atmos_model.F90
This upgrade ensures SHiELD receives valid surface air-sea fluxes calculated only over ocean points. This is crucial for real-world coupled SHiELD-MOM6 simulations, as there is no valid values for the surface fluxes over land points.
=> Updates to ensure only valid surface data are passed to SHiELD physics via the Coupler

SHiELDFULL/atmos_model.F90
Bare minimum changes needed for SHiELDFULL/atmos_model.F90 so that SHiELD's shieldfull and shieldmom configurations can compile with FMScoupler 2025.02-alpha1
Tested on Gaea with SHiELD_build tests
**Checklist:**
=> Bare minimum changes needed for SHiELDFULL coupler to compile with 2025.02-alpha1 (fmscoupler)

SHiELD/atmos_model.F90, SHiELDFULL/atmos_model.F90
Updating atmos_model.F90 to use diag_send_complete which is required when using the modern diag magager from FMS.  Without this update, when you try to use the modern diag manager (in input.nml `diag_manager_nml: use_modern_diag = .T.`) the model crashes at runtime.
Fixes #55 
Tested on Gaea:
ran with 64bit and 32 bit with and without modern diag manager.
**Checklist:**
=> Diag_manager fix for FMS modern diag_manager

SHiELD/atmos_model.F90, SHiELDFULL/atmos_model.F90, coupled/atmos_model.F90, solo/atmos_model.F90
updates the `error_mesg` and `check_nml_error` routines to use the fms prefix
compiled aquaplanet with this branch + my updates for FMS and the coupler 
**Checklist:**
=> change aliases for fms global module
